# Generated by Django 4.1.7 on 2023-03-31 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=150)),
                ('what', models.CharField(max_length=150)),
                ('where', models.CharField(max_length=100)),
                ('when', models.CharField(max_length=150)),
                ('why', models.TextField(max_length=250)),
            ],
        ),
    ]
