# Generated by Django 4.1.7 on 2023-04-06 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='polls',
        ),
        migrations.AddField(
            model_name='poll',
            name='event',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main_app.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='when',
            field=models.CharField(max_length=150),
        ),
    ]
