# Generated by Django 4.1.7 on 2023-04-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_poll_event_event_polls_group_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='when',
            field=models.CharField(max_length=150),
        ),
    ]
