# Generated by Django 4.1.7 on 2023-04-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_event_polls_poll_event_alter_event_when'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='creator',
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
