# Generated by Django 4.1.7 on 2023-04-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_event_name_event_user_alter_event_when'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='choice_one_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='choice_three_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='choice_two_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='choice_one',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='choice_three',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='choice_two',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
