# Generated by Django 4.1.7 on 2023-04-05 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_poll_choice_one_count_poll_choice_three_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.event'),
            preserve_default=False,
        ),
    ]
